name = "PrivateEncapsulation"
uuid = "acc5d4cc-5d5c-45c0-b1b0-dce7256bafe8"
authors = ["Nathan Daly <nathan.daly@relational.ai> and contributors"]
version = "1.0.0-DEV"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.10"
MacroTools = "0.5"
ReTestItems = "1"

[extras]
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ReTestItems","Test"]
