name = "PrivateEncapsulation"
uuid = "acc5d4cc-5d5c-45c0-b1b0-dce7256bafe8"
authors = ["Nathan Daly <nathan.daly@relational.ai> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
